# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0029_auto_20170321_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='estatus',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id_profesor',
            field=models.ForeignKey(default='null', null=True, on_delete=django.db.models.deletion.CASCADE, to='consultas.Profesor'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id_semestre',
            field=models.ForeignKey(default='null', null=True, on_delete=django.db.models.deletion.CASCADE, to='consultas.Semestre'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellidos',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombres',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='calendario',
            field=models.CharField(default='', max_length=3),
        ),
    ]
