# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 03:08
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('consultas', '0030_auto_20170327_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=100)),
                ('acronimo', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Carrera')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
            ],
            options={
                'proxy': True,
                'ordering': ('last_name',),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='id_coordinador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultas.Coordinador'),
        ),
    ]
