# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0032_auto_20170402_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='acronimo',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
