# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 06:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0033_auto_20170402_2240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinador',
        ),
        migrations.AlterField(
            model_name='carrera',
            name='id_coordinador',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
