# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0035_auto_20170403_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia_Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Carrera')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Materia')),
            ],
        ),
    ]
